# Generated by Django 2.1.1 on 2018-10-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coins',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=500)),
                ('curr_price', models.FloatField()),
                ('market_cap', models.FloatField()),
                ('market_cap_rank', models.IntegerField()),
                ('total_volume', models.FloatField()),
                ('high_24h', models.FloatField()),
                ('low_24h', models.FloatField()),
                ('price_change_24h', models.FloatField()),
                ('price_change_percentage_24h', models.FloatField()),
                ('market_cap_change_24h', models.FloatField()),
                ('market_cap_change_percentage_24h', models.FloatField()),
                ('circulating_supply', models.FloatField()),
                ('ath', models.FloatField()),
                ('ath_change_percentage', models.FloatField()),
                ('ath_date', models.DateTimeField()),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
