# Generated by Django 2.1.1 on 2018-11-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_auto_20181104_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins',
            name='total_supply',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
